-- insert into users(username, password, role) values ('admin', '1', 'ADMIN');
-- insert into users(username, password, role) values ('def_user', '1', 'DEFAULT_USER');
-- insert into users(username, password, role) values ('seller', '1', 'SELLER');
-- insert into users(username, password, role) values ('warehouseman', '1', 'WAREHOUSEMAN');
-- insert into users(username, password, role) values ('supervisor', '1', 'SUPERVISOR');

-- insert into category(name) values ('Lip products');
-- insert into category(name) values ('Eye makeup');
-- insert into category(name) values ('Hair products');
-- insert into category(name) values ('Nail polish and remover');
-- insert into category(name) values ('Fragrance and Perfumed products');
-- insert into category(name) values ('Body products');
-- insert into category(name) values ('Face products');
-- insert into category(name) values ('Cleaners and washers');
-- insert into category(name) values ('Soaps');
-- insert into category(name) values ('General makeup');